# Generated by Django 3.1.4 on 2021-01-07 14:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('year', models.IntegerField()),
                ('abstract', models.TextField(max_length=100000)),
                ('authors', models.CharField(max_length=1000)),
                ('conf', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('scanned', models.BooleanField()),
                ('todo', models.BooleanField()),
                ('read', models.BooleanField()),
                ('never', models.BooleanField()),
            ],
        ),
    ]
