# Generated by Django 3.1.4 on 2021-01-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_engine', '0002_auto_20210107_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('deadline', models.DateField()),
                ('done', models.BooleanField()),
                ('todo', models.BooleanField()),
                ('urgent', models.BooleanField()),
                ('important', models.BooleanField()),
            ],
        ),
    ]
